[book]
authors = ["Marcial Machado"]
language = "en"
multilingual = false
src = "legislature-book"
title = "Open Source Club at the Ohio State University"

[output.html]
default-theme = "light"
preferred-dark-theme = "coal"
git-repository-url = "https://github.com/OSUOSC/management-legislature"
